import { getCandidates } from "@/utils/data";

export const metadata = {
  title: "Seguimiento de Candidatos",
  description: "Generated by create next app",
};

export default async function Page() {
  const data = await getCandidates();

  return <>a</>;
}
