import { ThemeProvider } from "@/providers/theme-provider";
import { Toaster } from "react-hot-toast";
import "./globals.css";

export const metadata = {
  title: "HR SaaS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Toaster position="bottom-center" />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
