import { MainSidebar } from "@/components/layout/MainSidebar";

export const metadata = {
  title: "HR SaaS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return <MainSidebar>{children}</MainSidebar>;
}
