import { CandidatesDataTable } from "@/components/DataTables/CandidatesDataTable";
import { CandidatesColumns } from "@/components/DataTables/columns/CandidatesColumns";
import { getCandidates } from "@/utils/data";

export const metadata = {
  title: "Seguimiento de Candidatos",
  description: "Generated by create next app",
};

export default async function Page() {
  const data = await getCandidates();

  return (
    <>
      <div className="flex justify-between">
        <h1 className="text-xl font-medium">Candidatos Analizados</h1>
        <a
          href="/"
          className="bg-primary hover:bg-blue-500 items-center justify-center  rounded-full h-10 w-10 flex transition-all ease-in-out"
        >
          a
        </a>
      </div>
      <CandidatesDataTable columns={CandidatesColumns} candidates={data} />
    </>
  );
}
