import { CandidatesDataTable } from "@/components/DataTables/CandidatesDataTable";
import { CandidatesColumns } from "@/components/DataTables/columns/CandidatesColumns";
import { NewRecordLink } from "@/components/links/NewRecordLink";
import { getCandidates } from "@/utils/data";

export const metadata = {
  title: "Seguimiento de Candidatos",
  description: "Generated by create next app",
};

export default async function Page() {
  const data = await getCandidates();

  return (
    <>
      <div className="flex justify-between">
        <h1 className="text-xl font-medium">Candidatos Analizados</h1>
        <NewRecordLink href="/organizacion/ats/nuevo" />
      </div>
      <CandidatesDataTable columns={CandidatesColumns} candidates={data} />
    </>
  );
}
