import { JobForm } from "@/components/forms/JobForm";

export const metadata = {
  title: "Cargos",
  description: "Generated by create next app",
};

export default function Page() {
  return <JobForm />;
}
