import { BackButton } from "@/components/buttons/BackButton";
import { JobColumns } from "@/components/DataTables/columns/JobColumns";
import { JobDataTable } from "@/components/DataTables/JobDataTable";
import { JobForm } from "@/components/forms/JobForm";
import { getJobs } from "@/utils/data/Jobs";
import { readPrompts } from "@/utils/readPrompts";
import Link from "next/link";

export const metadata = {
  title: "Cargos",
  description: "Generated by create next app",
};

export default async function Page() {
  const jobs = await getJobs();

  return (
    <>
      <div className="flex justify-between">
        <h1 className="text-xl font-medium">Candidatos Analizados</h1>
        <Link
          href="/organizacion/cargos/nuevo"
          className="bg-primary hover:bg-blue-500 items-center justify-center  rounded-full h-10 w-10 flex transition-all ease-in-out"
        >
          Crear Nuevo
        </Link>
      </div>
      <JobDataTable jobs={jobs} columns={JobColumns} />
    </>
  );
}
