import { BackButton } from "@/components/buttons/BackButton";
import { JobColumns } from "@/components/DataTables/columns/JobColumns";
import { JobDataTable } from "@/components/DataTables/JobDataTable";
import { JobForm } from "@/components/forms/JobForm";
import { NewRecordLink } from "@/components/links/NewRecordLink";
import { getJobs } from "@/utils/data/Jobs";
import Link from "next/link";

export const metadata = {
  title: "Cargos",
  description: "Generated by create next app",
};

export default async function Page() {
  const jobs = await getJobs();

  return (
    <>
      <div className="flex justify-between">
        <h1 className="text-xl font-medium">Descripciones de Cargo</h1>
        <NewRecordLink href="/organizacion/cargos/nuevo" />
      </div>
      <JobDataTable jobs={jobs} columns={JobColumns} />
    </>
  );
}
